- name: Firewalld Installation
  yum:
    name: firewalld

- name: Firewalld start and enabled
  systemd:
    name: firewalld
    enabled: true

- name: Permit SSH
  firewalld:
    service: ssh
    permanent: true
    state: enabled

- name: Permit HTTP
  firewalld:
    service: http
    permanent: true
    state: enabled

- name: Permit HTTPS
  firewalld:
    service: https
    permanent: true
    state: enabled

- block:
  - name: Displaying the status
    command: systemctl status firewalld
    register: firewalld_service

  - debug:
       msg="{{ firewalld_service }}"

  - name: Displaying the status
    command: firewall-cmd --list-services
    register: allowed_services

  - debug:
      msg="{{ allowed_services }}"



